In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('./data/thai_words_in_zon.csv')

In [4]:
df

                 word label
0                  กก   NaN
1                 กขน   NaN
2                  กค   NaN
3                  กง   NaN
4                 กซ์   NaN
5                  กฎ   NaN
6              กฎหมาย     1
7             กฎเกณฑ์     1
8                  กฏ   NaN
9               กดดัน   NaN
10             กดปุ่ม   NaN
11              กดหัว   NaN
12                 กท   NaN
13                กทม   NaN
14                 กน   NaN
15                กนก   NaN
16                 กบ   NaN
17                กปิ   NaN
18                กพส   NaN
19    กฟดกสดสฟฟสดสกสห   NaN
20                 กม   NaN
21                กยศ   NaN
22                 กร   NaN
23                กรก   NaN
24            กรกฎาคม     1
25                กรง   NaN
26               กรณี   NaN
27                กรน   NaN
28                กรม   NaN
29             กรมท่า     1
...               ...   ...
7772              ไอ่   NaN
7773              ไอ้   NaN
7774           ไอ้บ้า   NaN
7775               ไฮ    1\
7776          ไฮเปอร์     1
7777             ไฮโซ     1
7778           ไฮไลต์     1
7779              ไีร   NaN
7780              ไเ้   NaN
7781               ไ้   NaN
7782             ไ้ด้   NaN
7783                ่   NaN
7784               ่า   NaN
7785              ่าน   NaN
7786                ้   NaN
7787                ์   NaN
7788               ์ก   NaN
7789               ์ค   NaN
7790               ์ณ   NaN
7791               ์ท   NaN
7792               ์ป   NaN
7793             ์ปคน   NaN
7794               ์ฟ   NaN
7795              ์มธ   NaN
7796               ์ย   NaN
7797              ์อฟ   NaN
7798             ์เฟส   NaN
7799                4   NaN
7800                5   NaN
7801                9   NaN

[7802 rows x 2 columns]